---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hello
    spec:
      containers:
        - name: flux-test
          image: openebs/flux-test:master-a000001
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: hello-service
spec:
  ports:
    - port: 8080
      nodePort: 32424
  selector:
    name: hello
  sessionAffinity: None
  type: NodePort 
