name: build-n-deploy

on:
  pull_request:
    branches: [ master ]

jobs:
  build-n-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - uses: okteto/actions/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        
    - uses: okteto/actions/namespace@master

    - name: Deploy Stack
      uses: okteto/actions/deploy-stack@master
      with: 
        build: "true"
        name: "hello-${{ github.event.number }}"
        
    - name: comment on PR
      uses: unsplash/comment-on-pr@v1.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "Review the changes live at: https://hello-ksatchit.cloud.okteto.net/"
      
